---
- hosts: k8s-master
  remote_user: ubuntu
  private_key_file: /etc/ansible/satya.pem
  become: yes
  gather_facts: no
  tasks:
   - name: copy k8s files
     copy:
       src: "{{ item }}"
       dest: /tmp/
     loop:
      - deployment.yml
      - service.yml
   - name: create deployment
     shell: kubectl apply -f deployment.yml
     args:
       chdir: /tmp/
   - name: create service
     shell: kubectl apply -f service.yml
     args:
       chdir: /tmp/
